# Use the official Node.js image as the base image
FROM node:18 as build

# Set the working directory in the container
WORKDIR /frontend

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install project dependencies
RUN npm install
RUN npm install -g @angular/cli@17.1.0
RUN npm install --save @angular/material @angular/cdk
RUN npm install --save @angular/animations
# Copy the entire project to the container
COPY . .

# Build the Angular app for production
RUN ng build

# Use a smaller, production-ready image as the final image
FROM nginx:alpine

# Copy the production-ready Angular app to the Nginx webserver's root directory
COPY --from=build /frontend/dist/frontend/browser /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]